services:
  - type: web
    name: proxima-stem-space
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node server/minimal-test.js
    healthCheckPath: /api/health
    autoDeploy: true
    pullRequestPreviewsEnabled: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: FORCE_HTTPS
        value: "true"
      - key: SESSION_SECURE
        value: "true"
      - key: TRUST_PROXY
        value: "true" 