services:
  - type: web
    name: proxima-stem-space
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx tsx server/test-server.ts
    envVars:
      - key: NODE_ENV
        value: production
      - key: GHOST_URL
        value: https://proxima-stem-space.ghost.io
      - key: GHOST_ADMIN_API_KEY
        value: 1234567890abcdef1234567890abcdef12345678
      - key: GHOST_CONTENT_API_KEY
        value: 1234567890abcdef1234567890abcdef12345678
      - key: JWT_SECRET
        value: your-super-secret-jwt-key-change-this-in-production
      - key: STRIPE_SECRET_KEY
        value: sk_test_1234567890abcdef1234567890abcdef12345678
      - key: STRIPE_WEBHOOK_SECRET
        value: whsec_1234567890abcdef1234567890abcdef12345678
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_sZcWROjl9i6C@ep-black-frog-a8nomna0-pooler.eastus2.azure.neon.tech/neondb?sslmode=require
      - key: SESSION_SECRET
        value: your-super-secret-session-key-change-this-in-production 